-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") FROM MEMBER_PROFILE 
where MONTH(DATE_OF_BIRTH)="3" and GENDER = "W" and TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;